# Generated by Django 4.1.1 on 2022-09-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSeries', '0002_alter_disney_photo_alter_disney_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disney',
            name='photo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='hbo',
            name='photo',
            field=models.URLField(),
        ),
    ]
