# Generated by Django 4.1.1 on 2022-09-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSeries', '0003_alter_disney_photo_alter_hbo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField()),
                ('qualification', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField()),
                ('qualification', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
            ],
        ),
    ]
